package com.nexus_flow.core.sagas.domain.value_objects.saga_member;

import com.nexus_flow.core.ddd.Utils;

import java.time.ZonedDateTime;
import java.util.Objects;

public class SagaTriggeredOn {

    private ZonedDateTime value;

    private SagaTriggeredOn() {
    }

    public SagaTriggeredOn(ZonedDateTime value) {
        this.value = value;
    }

    public SagaTriggeredOn(String value) {
        this.value = Utils.stringToZonedDateTime(value);
    }

    public ZonedDateTime getValue() {
        return value;
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    // Watch out not autogenerated!!!!
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SagaTriggeredOn that = (SagaTriggeredOn) o;
        return Utils.dateToString(value).equals(Utils.dateToString(that.value));
    }

}
