/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    base
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "net.nexus-flow"
version = "0.0.1-SNAPSHOT"
description = "Nexus Flow"

subprojects {
    plugins.withType<JavaPlugin> {
        extensions.configure<JavaPluginExtension> {
            toolchain {
                languageVersion.set(JavaLanguageVersion.of(25))
            }
        }
        tasks.withType<JavaCompile>().configureEach {
            options.release.set(25)
            options.compilerArgs.addAll(listOf("--enable-preview", "-Xlint:all", "-Xdoclint:all,-missing"))
        }
        tasks.withType<Test>().configureEach {
            jvmArgs("--enable-preview")
        }
        tasks.withType<JavaExec>().configureEach {
            jvmArgs("--enable-preview")
        }
        tasks.withType<Javadoc>().configureEach {
            // Preview API references in Javadoc (e.g. StructuredTaskScope
            // in SyncDispatcher) require the --enable-preview / --release
            // pair for `javadoc` just like `javac`.
            options {
                this as StandardJavadocDocletOptions
                addBooleanOption("-enable-preview", true)
                addStringOption("-release", "25")
            }
        }
    }
}
