blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Research-Project-Team/shared-bounded/discussions
    about: This link refers to the discussions section of the Github project, where community support can be found.