/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    pmd
    alias(libs.plugins.spotbugs)
    alias(libs.plugins.spotless)
}

spotless {
    java {
        target(
            "src/main/java/**/*.java",
            "src/test/java/**/*.java"
        )

        targetExclude(
            "**/build/**",
            "**/generated/**",
            "**/src/generated/**"
        )

        // expandWildcardImports() — temporarily disabled. The codebase has ~60 existing
        // `import x.*;` lines (mostly `Assertions.*` in tests) and the Spotless step needs a
        // JavaParser SymbolResolver to expand them, which isn't wired up here. Re-enable as a
        // follow-up chore: either expand the wildcards manually, or configure the resolver.
        removeUnusedImports()
        importOrder()

        eclipse(libs.versions.eclipse.jdt.get()).configFile(
            rootProject.file("config/eclipse/nexus-eclipse-jdt-formatter.xml")
        )

        formatAnnotations()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.java.get()))
    }
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    api(libs.jspecify)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.awaitility)
    testRuntimeOnly(libs.junit.platform.launcher)
}

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

publishing {
    publications {
        publications.create<MavenPublication>("maven") {
            from(components["java"])
            groupId = "net.nexus-flow"
            artifactId = "nexusflow-core"
            version = "0.0.1-SNAPSHOT"
            artifact(testsJar)
        }
    }
}

tasks.named("build") {
    finalizedBy("publishToMavenLocal")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    maxHeapSize = "1G"
    testLogging {
        events("passed", "failed", "skipped")
    }
}

pmd {
    isConsoleOutput = true
    toolVersion = libs.versions.pmd.get()
    rulesMinimumPriority.set(3)
    ruleSetFiles = files("pmd-rules.xml")
    ruleSets = listOf()   // clear defaults; use only pmd-rules.xml
}

spotbugs {
    toolVersion.set(libs.versions.spotbugs.tool.get())
    effort.set(com.github.spotbugs.snom.Effort.MAX)
    reportLevel.set(com.github.spotbugs.snom.Confidence.LOW)
    excludeFilter.set(file("spotbugs-exclude.xml"))
    ignoreFailures.set(true)
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    reports.create("html") { required.set(true) }
    reports.create("xml") { required.set(false) }
}
