/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
}

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.java.get()))
    }
}

dependencies {
    implementation(project(":project:core"))
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    maxHeapSize = "1G"
    testLogging {
        events("passed", "failed", "skipped")
    }
}

tasks.register<JavaExec>("runDemo") {
    group = "application"
    description = "Run the Nexus Flow demo application."
    mainClass.set("net.nexus_flow.NexusFlowDemo")
    classpath = sourceSets["main"].runtimeClasspath
    jvmArgs(
        "-Dfile.encoding=UTF-8",
        "-Dsun.stdout.encoding=UTF-8",
        "-Dsun.stderr.encoding=UTF-8",
        "-Duser.language=en",
        "-Duser.country=US",
        "-DeventContextStrategy=scoped",
        // Demos are short-lived smoke runs (sub-second of actual work). Skipping the C2
        // tier removes 1-2 s of cold-start compilation overhead that the dispatch hot path
        // would never benefit from inside a single demo invocation. Drop this flag for any
        // long-running benchmark or production launch — full tiered compilation matters
        // there.
        "-XX:TieredStopAtLevel=1"
    )
}

tasks.register<JavaExec>("runAdvancedDemo") {
    group = "application"
    description = "Run the advanced Nexus Flow demo (outbox, saga, dead-letter, audit trail)."
    mainClass.set("net.nexus_flow.advanced.NexusFlowAdvancedDemo")
    classpath = sourceSets["main"].runtimeClasspath
    jvmArgs(
        "-Dfile.encoding=UTF-8",
        "-Dsun.stdout.encoding=UTF-8",
        "-Dsun.stderr.encoding=UTF-8",
        "-Duser.language=en",
        "-Duser.country=US",
        "-DeventContextStrategy=scoped",
        // Demos are short-lived smoke runs (sub-second of actual work). Skipping the C2
        // tier removes 1-2 s of cold-start compilation overhead that the dispatch hot path
        // would never benefit from inside a single demo invocation. Drop this flag for any
        // long-running benchmark or production launch — full tiered compilation matters
        // there.
        "-XX:TieredStopAtLevel=1"
    )
}
