/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(project(":project:core"))
}

java.sourceCompatibility = JavaVersion.VERSION_21

tasks.withType<JavaCompile> {
    val compilerArgs = options.compilerArgs
    compilerArgs.add("-Xdoclint:all,-missing")
    compilerArgs.add("-Xlint:all")
}

tasks.named<Test>("test") {
    useJUnitPlatform()

    maxHeapSize = "1G"

    testLogging {
        events("passed")
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("--enable-preview")
}

tasks.register<JavaExec>("runDemo") {
    group = "application"
    mainClass.set("org.nexusflow.NexusFlowDemo")
    classpath = sourceSets["main"].runtimeClasspath
    args = listOf("-DeventContextStrategy=scoped")
}

tasks.withType<JavaExec>().configureEach {
    jvmArgs("--enable-preview")
}
