/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    application
}

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.java.get()))
    }
}

dependencies {
    implementation(project(":project:core"))
}

application {
    mainClass.set("net.nexus_flow.NexusFlowDemo")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    maxHeapSize = "1G"
    testLogging {
        events("passed", "failed", "skipped")
    }
}

tasks.register<JavaExec>("runDemo") {
    group = "application"
    description = "Run the Nexus Flow demo application."
    mainClass.set("net.nexus_flow.NexusFlowDemo")
    classpath = sourceSets["main"].runtimeClasspath
    jvmArgs(
        "-Dfile.encoding=UTF-8",
        "-Dsun.stdout.encoding=UTF-8",
        "-Dsun.stderr.encoding=UTF-8",
        "-Duser.language=en",
        "-Duser.country=US",
        "-DeventContextStrategy=scoped"
    )
}
