package net.nexus_flow.core.runtime.ids;

import java.util.Objects;

/**
 * Multi-tenant boundary identifier propagated through every dispatch via {@link
 * net.nexus_flow.core.runtime.ExecutionContext#tenant()}.
 *
 * <p>Unlike {@link MessageId} / {@link TraceId} / {@link CorrelationId} (which are technical UUIDs
 * generated by the runtime), {@code TenantId} carries a caller-supplied <strong>opaque
 * string</strong>: a customer slug, an organisation UUID, a Kubernetes namespace, a database schema
 * name — whatever shape the host application uses to slice its data and metering.
 *
 * <p>The value is required to be non-blank: an empty or whitespace-only tenant identifier is almost
 * always a bug (a tag that silently degrades to "no tenant" defeats every per-tenant dashboard and
 * isolation policy). Callers that genuinely want "no tenant" pass {@code null} to {@link
 * net.nexus_flow.core.runtime.ExecutionContext} rather than constructing an empty {@code TenantId}.
 *
 * <p><strong>Wire format.</strong> The {@code TenantId} value is persisted verbatim by the outbox
 * ({@link net.nexus_flow.core.outbox.OutboxRecord#tenantId()}) so that worker re-publish on restart
 * restores the same tenant scope. Adapters that ship a JDBC backend should map this to a {@code
 * VARCHAR} column with the same casing/length constraints applied by the host.
 *
 * <p><strong>Equality.</strong> Two {@code TenantId} instances are equal iff their {@code value}
 * strings are equal. No case-folding is applied: {@code TenantId.of("acme")} is NOT equal to {@code
 * TenantId.of("Acme")}. Hosts that need case-insensitive equality canonicalise to lowercase before
 * constructing.
 *
 * @param value the opaque tenant identifier; must not be {@code null} or blank
 */
public record TenantId(String value) {

    public TenantId {
        Objects.requireNonNull(value, "value");
        if (value.isBlank()) {
            throw new IllegalArgumentException("TenantId value must not be blank");
        }
    }

    /**
     * Convenience factory mirroring the other {@code Id.of(...)} factories.
     *
     * @param value the opaque tenant identifier; must not be {@code null} or blank
     * @return a new {@code TenantId} wrapping {@code value}
     */
    public static TenantId of(String value) {
        return new TenantId(value);
    }

    @Override
    public String toString() {
        return value;
    }
}
